name: shramic_community_web
description: Shramic Community Web Platform
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.0
  easy_localization: ^3.0.3
  flutter_animate: ^4.3.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/
