name: Deploy Shramic Community Web Application

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest   

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf *
            git clone https://github.com/udaykumar2624/shramic-community-web.git
            cd shramic-community-web
            docker-compose down -v
            docker system prune -a -f
            
