name: deploy Shramic_community_webapplication

on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH
       uses: appleboy/ssh-action@v1.0.3
       with:
         host: ${{ secrets.SSH_HOST }}
         username: root
         key: ${{ secrets.SSH_KEY }}
         script:
           cd /root
           git pull
           docker compose up -d --build
